### ISSUE TITLE
Makeing part of CppAD

### ISSUE THREAD

**Issue by bradbell** [perrydv/TBB4CppAD#1]

**Comment by bradbell** [comment]
I suggest that you create a team of threads using TBB; see
http://coin-or.github.io/CppAD/doc/team_thread.hpp.htm

You then should be able to create a subdirectory called
example/multi_thread/tbb

that is similar to the directories
example/multi_thread/openmp
example/multi_thread/pthread
example/multi_thread/bthread

and which runs the CppAD multi-threading correctness and speed tests.

**Comment by perrydv** [comment]
Oops, I left this issue open.  Thanks for the suggestion.  Setting up a team of threads to match the other examples would have been easier, but TBB isn't really designed around that concept. It abstracts away thread management.
